
# board
BOARD_SIZE = 15

# train
RECENT_COUNT = 10000
BATCH_SIZE = 256
LEARING_RATE = 1E-3
FILTERS = 32
VALUE_HIDDEN_UNITS = 128
BATCHNORM_MOMENTUM = 0.1  # decay=0.9
WEIGHT_COUNT = 2
WEIGHT_EPOCH = 1

# selfplay
SELFPLAY_PROCESS_COUNT = 5
SELFPLAY_TARGET_ROUNDS = 500

# evaluator
EVAL_PROCESS_COUNT = 5
EVAL_TARGET_ROUNDS = 50